name: Beauty Tech CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Frontend Dependencies
      run: npm install
      
    - name: Install Backend Dependencies
      run: |
        cd api
        npm install

    - name: Run Frontend Lint
      run: |
        npm install eslint --save-dev
        npx eslint . --ext .js

    - name: Run Backend Tests
      run: |
        cd api
        npm test
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}

    - name: Check Frontend Build
      run: |
        npm run build --if-present

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to Production
      run: echo "Aqui você pode adicionar os comandos para deploy em produção"
      # Exemplo de deploy para serviços como Heroku, Vercel, etc.
